IP_ADDRESS: 127.0.0.1

REDIS_HOST: ${IP_ADDRESS}
REDIS_PORT: 6379

RABBIT_MQ_HOST: ${IP_ADDRESS}
RABBIT_MQ_PORT: 5672

MYSQL_HOST: ${IP_ADDRESS}
MYSQL_PORT: 3306

EUREKA_HOST: ${IP_ADDRESS}
EUREKA_PORT: 7001

spring:
    application:
        name: ace-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        pool:
        max-active: 20
    datasource:
      name: test
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/ag_auth_v1?useUnicode=true&characterEncoding=UTF8
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    rabbitmq:
      host: ${RABBIT_MQ_HOST}
      port:  ${RABBIT_MQ_PORT}
      username: guest
      password: guest
    sleuth:
      enabled: true
      http:
        legacy:
          enabled: true

mybatis:
    basepackage: com.mfg.authserver.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
    port: 9777 #启动端口

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: ${IP_ADDRESS}
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/



jwt:
  token-header: Authorization
  expire: 14400    #4个小时过期 生成的JWT Token的过期时间
  rsa-secret: xx1WET12^%3^(WE45        #用户密钥

client:
  id: ace-auth
  secret: 123456
  token-header: x-client-token
  expire: 14400    #生成的client客户端token过期时间
  rsa-secret: x2318^^(*WRYQWR(QW&T    #客户端密钥

logging:
    level:
#        tk.mybatis: DEBUG
        com.mfg.authserver: DEBUG