IP_ADDRESS: 172.30.1.81
#IP_ADDRESS: 127.0.0.1

REDIS_HOST: ${IP_ADDRESS}
REDIS_PORT: 6379

RABBIT_MQ_HOST: ${IP_ADDRESS}
RABBIT_MQ_PORT: 5672

MYSQL_HOST: ${IP_ADDRESS}
MYSQL_PORT: 3306

EUREKA_HOST: ${IP_ADDRESS}
EUREKA_PORT: 7001


server:
  port: 8765
eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /

  client:
    serviceUrl:
  #            defaultZone: http://localhost:8761/eureka/
                      # docker 部署开启
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
      name: ace-gateway-v2
  redis:
      database: 1
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      jedis:
        pool:
            max-active: 20
  rabbitmq:
      host: ${RABBIT_MQ_HOST}
      port:  ${RABBIT_MQ_PORT}
      username: guest
      password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # =====================================
      - id: ace-auth
        uri: lb://ace-auth
        order: 8000
        predicates:
        - Path=/api/auth/**
        filters:
        - StripPrefix=2
      - id: ace-admin
        uri: lb://ace-admin
        order: 8001
        predicates:
        - Path=/api/admin/**
        filters:
        - StripPrefix=2
      - id: ace-asset
        uri: lb://ace-asset
        order: 8002
        predicates:
        - Path=/api/asset/**
        filters:
        - StripPrefix=2

logging:
  level:
    com.mfg.auth.gate.v2: info

#自定义的变量
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
     gateway:
       enabled: true
  security:
    enabled: false

#自定义的变量
gate:
  ignore:
    startWith: /auth/jwt,/asset/employee/employeeUrl,/asset/employee/uploadimg,/asset/employee/qrCode

#自定义的变量
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: ace-gate  #不填则默认读取spring.application.name
    secret: 123456